version: "3.9"
services:
  pg:
    image: postgres:14-alpine
    container_name: pg
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data_volume:/data/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname=${DB} --username=${USER}
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rsoi1
    container_name: crud-app
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - "8080:1234"
    environment:
      HOST: ${POSTGRES_HOST}
      PORT: ${POSTGRES_PORT}
      DB: ${POSTGRES_DB}
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  pg_data_volume:
