version: "3.9"
services:
  pg:
    image: postgres:14-alpine
    container_name: pg
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
      PGDATA: "/data/lib/postgresql/data/pgdata"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname=$DB --username=$USER
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rsoi1
    container_name: crud-app
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8080:1234"
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB: ${DB}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
volumes:
  pg_data_volume:
